"""Initial migration

Revision ID: 2dfc5abaaaa4
Revises: 
Create Date: 2026-01-20 00:44:43.753063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2dfc5abaaaa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create new payment_transactions table
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('transaction_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('midtrans_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    
    # Migrate data from old 'transactions' table if it exists
    # Check if old table exists before trying to migrate
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    tables = inspector.get_table_names()
    
    if 'transactions' in tables:
        # Migrate data from old table to new table
        op.execute("""
            INSERT INTO payment_transactions (user_id, order_id, plan_id, amount, status, payment_type, created_at, updated_at)
            SELECT 
                user_id,
                order_id,
                plan_id,
                amount,
                COALESCE(status, 'pending'),
                'qris' as payment_type,
                COALESCE(created_at, NOW()),
                COALESCE(updated_at, NOW())
            FROM transactions
            WHERE NOT EXISTS (
                SELECT 1 FROM payment_transactions WHERE payment_transactions.order_id = transactions.order_id
            )
        """)
        
        # Now drop old table
        op.drop_table('transactions')
    
    # Update user_quotas table
    # Check if created_at column already exists
    if 'user_quotas' in tables:
        columns = [col['name'] for col in inspector.get_columns('user_quotas')]
        if 'created_at' not in columns:
            op.add_column('user_quotas', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        
        # Alter existing columns
        op.alter_column('user_quotas', 'requests_remaining',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_server_default=sa.text('0'))
        op.alter_column('user_quotas', 'total_requests',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_server_default=sa.text('0'))
        op.alter_column('user_quotas', 'is_premium',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_server_default=sa.text('false'))
        op.alter_column('user_quotas', 'updated_at',
                   existing_type=postgresql.TIMESTAMP(),
                   type_=sa.DateTime(timezone=True),
                   nullable=False,
                   existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        
        # Create index if not exists
        indexes = [idx['name'] for idx in inspector.get_indexes('user_quotas')]
        if 'ix_user_quotas_user_id' not in indexes:
            op.create_index(op.f('ix_user_quotas_user_id'), 'user_quotas', ['user_id'], unique=False)
    else:
        # Create user_quotas table if it doesn't exist
        op.create_table('user_quotas',
            sa.Column('user_id', sa.String(length=255), nullable=False),
            sa.Column('requests_remaining', sa.Integer(), server_default='0', nullable=False),
            sa.Column('total_requests', sa.Integer(), server_default='0', nullable=False),
            sa.Column('username', sa.String(length=255), nullable=True),
            sa.Column('first_name', sa.String(length=255), nullable=True),
            sa.Column('last_name', sa.String(length=255), nullable=True),
            sa.Column('language_code', sa.String(length=10), nullable=True),
            sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('user_id')
        )
        op.create_index(op.f('ix_user_quotas_user_id'), 'user_quotas', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_quotas_user_id'), table_name='user_quotas')
    op.alter_column('user_quotas', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_quotas', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_quotas', 'total_requests',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_quotas', 'requests_remaining',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('user_quotas', 'created_at')
    
    # Migrate data back before dropping
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    tables = inspector.get_table_names()
    
    if 'payment_transactions' in tables:
        # Create old transactions table
        op.create_table('transactions',
        sa.Column('order_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('plan_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
        sa.Column('payment_url', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('snap_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('order_id', name=op.f('transactions_pkey'))
        )
        
        # Migrate data back
        op.execute("""
            INSERT INTO transactions (order_id, user_id, plan_id, amount, status, created_at, updated_at)
            SELECT order_id, user_id, plan_id, amount, status, created_at, updated_at
            FROM payment_transactions
        """)
    
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
